#!/usr/bin/env python3

import argparse
import configparser
from datetime import datetime, timedelta
import socket
import time
import re
import threading
import signal

from email.mime.text import MIMEText
from subprocess import Popen, PIPE

CHECK_INTERVAL = 20


class Protocol:
    def __init__(self, proto_name, proto_type, proto_table, proto_state, proto_since, proto_info):
        self.name = proto_name
        self.type = proto_type
        self.table = proto_table
        self.state = proto_state
        self.since = proto_since
        self.info = proto_info

    def __str__(self):
        return 'Protocol<%s:%s>:%s' % (self.type, self.name, self.state)


class ProtocolHandler:
    def __init__(self, socket_alias, interesting_protocols, notification_delay, mailer):
        self.socket_alias = socket_alias
        self.interesting_protocols = interesting_protocols
        self.notification_delay = notification_delay
        self.mailer = mailer
        self.last_state = {}  # protocol state after last update
        self.last_alert_state = {}  # protocol state that was sent in the last alert
        self.alert_time = {}  # time when an alert should be sent for this protocol
        self.protocol_log = {}  # storage for actual Protocol object (to obtain detailed info later)
        self.touched = []  # protocols that were present in last update

    def update(self, protocols):
        self.touched = []
        self.inject_protocols(protocols)
        self.find_vanished()
        self.alert_for_changes()

    def inject_protocol(self, protocol):
        if type(protocol) is not Protocol:
            raise TypeError

        if protocol.type not in self.interesting_protocols:
            return

        self.touched.append(protocol.name)

        self.protocol_log[protocol.name] = protocol

        if protocol.name not in self.last_state:
            self.last_state[protocol.name] = 'absent'
            self.last_alert_state[protocol.name] = 'absent'

        if protocol.state != self.last_state[protocol.name]:
            # changed
            print(
                '%s: Protocol %s has changed from %s to %s' % (
                    self.socket_alias,
                    protocol.name,
                    self.last_state[protocol.name],
                    protocol.state
                )
            )
            self.last_state[protocol.name] = protocol.state
            self.alert_time[protocol.name] = datetime.now() + self.notification_delay

    def inject_protocols(self, protocols):
        if type(protocols) is not list:
            raise TypeError

        for protocol in protocols:
            self.inject_protocol(protocol)

    def purge_protocol(self, protocol_name):
        del self.last_state[protocol_name]
        del self.last_alert_state[protocol_name]
        del self.protocol_log[protocol_name]

    def find_vanished(self):
        for protocol in self.last_state:
            if self.last_state[protocol] != 'vanished' and protocol not in self.touched:
                # Protocol has vanished. Schedule an alert (that will also remove the protocol from our watch).
                print(
                    '%s: Protocol %s has changed from %s to %s' % (
                        self.socket_alias,
                        protocol,
                        self.last_state[protocol],
                        'vanished'
                    )
                )
                self.last_state[protocol] = 'vanished'
                self.alert_time[protocol] = datetime.now() + self.notification_delay

    def alert_for_changes(self):
        now_x = {}
        body = []

        for protocol in self.alert_time:
            if self.alert_time[protocol] and self.alert_time[protocol] <= datetime.now():
                self.alert_time[protocol] = None

                state = self.last_state[protocol]
                if state == self.last_alert_state[protocol]:
                    print(
                        '%s: Would issue alert for protocol %s, but it has returned to previous state (%s). Clearing alert flag.' % (self.socket_alias, protocol, state)
                    )
                    continue

                self.last_alert_state[protocol] = state

                proto = self.protocol_log[protocol]

                if state == 'vanished':
                    body += ['%-15s%-15s%-15s%-15s%-15s'
                             % (proto.name, proto.type, 'vanished', '', '')]
                    self.purge_protocol(protocol)

                else:
                    body += ['%-15s%-15s%-15s%-15s%-15s'
                             % (proto.name, proto.type, proto.state, proto.since, proto.info)]

                if state not in now_x:
                    now_x[state] = 1
                else:
                    now_x[state] += 1

        if now_x:
            body = ['%-15s%-15s%-15s%-15s%-15s'
                    % ('NAME', 'PROTOCOL', 'STATE', 'SINCE', 'INFO')] \
                   + body
            details = ', '.join(['%d %s' % (now_x[x], x) for x in now_x])
            self.mailer.send_notification_mail(self.socket_alias, details, '\n'.join(body))


def recvline(sock):
    response = b''
    b = b''
    while b != b'\n':
        b = sock.recv(1)
        response += b
    return response.decode('utf-8')


class Mailer:
    def __init__(self, hostname, from_addr, to_addr):
        self.hostname = hostname
        self.from_addr = from_addr
        self.to_addr = to_addr

    def send_notification_mail(self, socket_alias, details, body):
        subject = 'Birdwatch %s %s: %s' % (
            self.hostname,
            socket_alias,
            details
        )
        self.send_mail(subject, body)

    def send_mail(self, subject, body):
        msg = MIMEText(body)
        msg["From"] = self.from_addr
        msg["To"] = self.to_addr
        msg["Subject"] = subject
        print('Sending mail with subject "%s"' % subject)
        p = Popen(["sendmail", "-t", "-oi"], stdin=PIPE)
        p.communicate(msg.as_string().encode('utf-8'))


def watch_socket(socket_path, socket_alias, interesting_protocols, notification_delay, mailer, sigterm_handler):
    try:
        handler = ProtocolHandler(socket_alias, interesting_protocols, notification_delay, mailer)

        client = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
        client.connect(socket_path)

        preamble = recvline(client)
        if not (preamble.startswith('0001 BIRD ') and preamble.endswith('ready.\n')):
            raise Exception("Bird didn't send correct preamble on socket.")

        while True:
            client.send(b'show protocols\n')

            response = []
            line = ''
            while not line.startswith('0000'):
                line = recvline(client)
                line = re.sub(r'^(\d{4})-', r'\1 ', line)
                response += [line]

            protocols = []

            code = ''
            for line in response:
                parts = re.split('\s+', line)
                if parts[0]:
                    code = parts[0]
                if code == '1002':
                    proto_name, proto_type, proto_table, proto_state, proto_since, proto_info = parts[1:7]
                    proto = Protocol(proto_name, proto_type, proto_table, proto_state, proto_since, proto_info)
                    protocols.append(proto)

            handler.update(protocols)

            for i in range(CHECK_INTERVAL):
                if sigterm_handler.kill_now:
                    return
                time.sleep(1)

    except Exception as e:
        import traceback
        details = 'error'
        body = 'Lost connection to bird:\n%s' % traceback.format_exc()
        mailer.send_notification_mail(socket_alias, details, body)


class GracefulKiller:
    kill_now = False

    def __init__(self):
        signal.signal(signal.SIGINT, self.exit_gracefully)
        signal.signal(signal.SIGTERM, self.exit_gracefully)

    def exit_gracefully(self, signum, frame):
        print('Program now set to terminate after next cycle')
        self.kill_now = True


def main():
    parser = argparse.ArgumentParser(description='Simple protocol state monitoring for the Bird Internet Routing Daemon')
    parser.add_argument('-c', '--configfile',
                        type=argparse.FileType('r'),
                        default='./birdwatch.ini',
                        help='Path to a Birdwatch config file. Defaults to ./birdwatch.ini.')

    args = parser.parse_args()

    config = configparser.ConfigParser()
    config.optionxform = lambda option: option  # do not lowercase option names
    config.read_file(args.configfile)

    killer = GracefulKiller()

    interesting_protocols = []
    for protocol in config['protocols']:
        if config['protocols'][protocol] == "1":
            interesting_protocols.append(protocol)
    print('Considering protocol types: %s' % (', '.join(interesting_protocols)))

    notification_delay = timedelta(seconds=config.getint('birdwatch', 'notification_delay', fallback=120))

    system_hostname = socket.gethostname()
    from_addr = config.get(
        'mail', 'from',
        fallback='birdwatch@$HOSTNAME')\
        .replace('$HOSTNAME', system_hostname)
    to_addr = config.get(
        'mail', 'to',
        fallback='root') \
        .replace('$HOSTNAME', system_hostname)
    hostname = config.get(
        'birdwatch', 'hostname',
        fallback='$HOSTNAME') \
        .replace('$HOSTNAME', system_hostname)

    mailer = Mailer(hostname, from_addr, to_addr)

    for sock_name in config['sockets']:
        sock_path = config['sockets'][sock_name]
        print('Watching socket "%s" at "%s"' % (sock_name, sock_path))
        t = threading.Thread(
            target=watch_socket,
            args=(sock_path, sock_name, interesting_protocols, notification_delay, mailer, killer)
        )
        t.daemon = False
        t.start()


if __name__ == "__main__":
    main()
